# Site settings
title: Akshay Karle's blog
email: akshay.a.karle@gmail.com
description: "Young developer, linux lover, shaver of yaks."
baseurl: ""
url: "http://akshaykarle.com"
twitter_username: akshay_karle
github_username:  akshaykarle

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-sitemap
